### ISSUE TITLE
Setting up env failed

### ISSUE THREAD

**Issue by xxiexuezhi** [microsoft/frame-flow#13]
Dear sir,

Thx for your awsome work. I follow the instruction on env set up by running conda env create -f fm.yml. but I had the failed message as below. any suggestions would be very appreciated. 

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/numpy/core/__init__.py", line 22, in <module>
          from . import multiarray
        File "/tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/numpy/core/multiarray.py", line 12, in <module>
          from . import overrides
        File "/tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/numpy/core/overrides.py", line 7, in <module>
          from numpy.core._multiarray_umath import (
      ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/scratch/conda_scratch_pkg/env/fm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/scratch/conda_scratch_pkg/env/fm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/scratch/conda_scratch_pkg/env/fm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
        File "/tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/numpy/__init__.py", line 150, in <module>
          from . import core
        File "/tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/numpy/core/__init__.py", line 48, in <module>
          raise ImportError(msg)
      ImportError:
      
      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
      
      Importing the numpy C-extensions failed. This error can happen for
      many reasons, often due to issues with your setup or how NumPy was
      installed.
      
      We have compiled some common reasons and troubleshooting tips at:
      
          https://numpy.org/devdocs/user/troubleshooting-importerror.html
      
      Please note and check the following:
      
        * The Python version is: Python3.10 from "/home/scratch/conda_scratch_pkg/env/fm/bin/python"
        * The NumPy version is: "1.21.4"
      
      and make sure that they are the versions you expect.
      Please carefully study the documentation linked above for further help.
      
      Original error was: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/pip-build-env-vkfz21ku/overlay/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so)
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed

**Comment by jasonkyuyim** [comment]
Hi, are you sure this is an issue with our code? GLIBC_2.29 is a system package that needs to be installed separately.

**Comment by jasonkyuyim** [comment]
Closing due to no activity.
